services:

  db:  
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER} 
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: steel_time
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}  -d steel_time"] # pg_isready - встроенная утилита которая проверяет, что БД принимает соединения
      interval: 5s
      retries: 5
    volumes: 
      - postgres_data:/var/lib/postgresql/data # стандартное мето хранения файлов postgres (имя_volume:путь внутри контейнера)
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports: 
      - "8000:8000" # Формат: порт на пк: порт в контейнере
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Ждем пока БД будет реально готова к работе, а не просто стартовал контейнер
        
volumes:
  postgres_data: